version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./target/api-proc-arquivo-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/processamentoarquivo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@123
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: processamentoarquivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d/:ro

volumes:
  postgres_data: