version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./target/api-proc-arquivo-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/processamentoarquivo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@123
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: processamentoarquivo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/processamentoarquivo -schemas=public -user=postgres -password=postgres@123 migrate
    depends_on:
        postgres:
          condition: service_healthy
    volumes:
      - ./db/migration:/flyway/sql

volumes:
  postgres_data: